// <copyright file="PostOperationmsdyn_workorderservicetaskCreate.cs" company="">
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author>Hong Liu</author>
// <date>9/20/2018 10:21:27 AM</date>
// <summary>Implements the PostOperationmsdyn_workorderservicetaskCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using System;
using System.Linq;
using System.Web.Services.Description;

namespace TSIS2.Plugins
{

    [CrmPluginRegistration(
    MessageNameEnum.Create,
    "msdyn_workorderservicetask",
    StageEnum.PostOperation,
    ExecutionModeEnum.Synchronous,
    "",
    "TSIS2.Plugins.PostOperationmsdyn_workorderservicetaskCreate Plugin",
    1,
    IsolationModeEnum.Sandbox, 
    Description = "Copies the JSON Questionnaire Definition from a Service Task to a Work Order Service Task.")]
    /// <summary>
    /// PostOperationmsdyn_workorderservicetaskCreate Plugin.
    /// </summary>    
    public class PostOperationmsdyn_workorderservicetaskCreate : PluginBase
    {
        //private readonly string postImageAlias = "PostImage";
        private const string ROM_SERVICE = "- ROM Service / Service GSR";
        private const string QC_TASKTYPE_GUID = "931b334c-c55b-ee11-8df0-000d3af4f52a";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostOperationmsdyn_workorderservicetaskCreate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public PostOperationmsdyn_workorderservicetaskCreate(string unsecure, string secure)
            : base(typeof(PostOperationmsdyn_workorderservicetaskCreate))
        {
            //if (secure != null &&!secure.Equals(string.Empty))
            //{

            //}
        }

        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            Entity target = (Entity)context.InputParameters["Target"];

            //Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;
            localContext.Trace("Entering ExecuteCrmPlugin method.");
            try
            {
                // Log the system username at the start
                var systemUser = localContext.OrganizationService.Retrieve("systemuser", context.InitiatingUserId, new ColumnSet("fullname"));
                localContext.Trace("Plugin executed by user: {0}", systemUser.GetAttributeValue<string>("fullname"));

                localContext.Trace("PostOperationmsdyn_workorderservicetaskCreate: Begin.");

                if (string.Equals(systemUser.GetAttributeValue<string>("fullname"), ROM_SERVICE, StringComparison.OrdinalIgnoreCase))
                {

                    if (target.Attributes.Contains("msdyn_workorder") && target["msdyn_workorder"] != null && target.Attributes.Contains("msdyn_tasktype") && target["msdyn_tasktype"] != null)
                    {
                        EntityReference tasktype = (EntityReference)target["msdyn_tasktype"];

                        if (tasktype.Id != Guid.Parse(QC_TASKTYPE_GUID))
                        {
                            localContext.Trace("Task type is not QC, processing WOST.");
                            var workOrderRef = target.GetAttributeValue<EntityReference>("msdyn_workorder");

                            localContext.Trace("WOST is linked to Work Order. Id: {0}", workOrderRef.Id);

                            var workOrder = localContext.OrganizationService.Retrieve("msdyn_workorder", workOrderRef.Id, new ColumnSet("ownerid"));

                            if (workOrder.Contains("ownerid") && workOrder["ownerid"] != null)
                            {
                                var woOwner = workOrder.GetAttributeValue<EntityReference>("ownerid");

                                target["ownerid"] = woOwner;

                                localContext.Trace("Updating Work Order Service Task owner.");
                                localContext.OrganizationService.Update(target);


                                localContext.Trace("Retrieving Work Order Incidents for Work Order.");

                                var incidentQuery = new QueryExpression("msdyn_workorderincident")
                                {
                                    ColumnSet = new ColumnSet("msdyn_workorderincidentid", "ownerid"),
                                    Criteria ={Conditions ={new ConditionExpression("msdyn_workorder",ConditionOperator.Equal, workOrderRef.Id)}}
                                };

                                var incidents = localContext.OrganizationService.RetrieveMultiple(incidentQuery);

                                foreach (var incident in incidents.Entities)
                                {
                                    localContext.Trace(
                                        "Assigning Incident {0} owner to WO owner {1}.",
                                        incident.Id,
                                        woOwner.Id);

                                    var assignRequest = new AssignRequest
                                    {
                                        Target = incident.ToEntityReference(),
                                        Assignee = woOwner
                                    };

                                    localContext.OrganizationService.Execute(assignRequest);

                                }
                                // Trace after update
                                localContext.Trace("Work Order Service Task update complete.");
                            }
                            else
                            {
                                localContext.Trace("Work Order has no ownerid (unexpected).");
                            }
                        }
                    }
                    else
                    {
                        localContext.Trace("WOST does not contain msdyn_workorder lookup.");
                    }
                }
                if (target.LogicalName.Equals(msdyn_workorderservicetask.EntityLogicalName))
                {
                    if (target.Attributes.Contains("msdyn_tasktype") && target.Attributes["msdyn_tasktype"] != null)
                    {
                        EntityReference tasktype = (EntityReference)target.Attributes["msdyn_tasktype"];
                        using (var servicecontext = new Xrm(localContext.OrganizationService))
                        {
                            localContext.Trace("Task type found: {0}", tasktype.Id);
                            var rclegislations = (from tt in servicecontext.ovs_msdyn_servicetasktype_qm_rclegislationSet
                                                  join le in servicecontext.qm_rclegislationSet
                                                  on tt.qm_rclegislationid.Value equals le.qm_rclegislationId.Value
                                                   where tt.msdyn_servicetasktypeid == tasktype.Id
                                                   select new
                                                   {
                                                       tt.qm_rclegislationid,
                                                       le.qm_name
                                                   }).ToList();
                            foreach (var le in rclegislations)
                            {
                                if (le.qm_rclegislationid != null)
                                {
                                    ovs_workorderservicetaskprovision wp = new ovs_workorderservicetaskprovision();
                                    wp.ovs_ProvisionId = new EntityReference(qm_rclegislation.EntityLogicalName, le.qm_rclegislationid.Value);
                                    wp.ovs_WorkOrderServiceTaskId = new EntityReference(msdyn_workorderservicetask.EntityLogicalName, target.Id);
                                    wp.ovs_name = le.qm_name;
                                    localContext.OrganizationService.Create(wp);
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception e)
            {
                localContext.Trace("Exception occurred: {0}", e.ToString());
                throw new InvalidPluginExecutionException(e.Message);
            }
        }
    }
}