// <copyright file="PreOperationmsdyn_workorderCreate.cs" company="">
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author>Hong Liu</author>
// <date>9/20/2018 10:21:27 AM</date>
// <summary>Implements the PreOperationmsdyn_workorderCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using System.Linq;
using Microsoft.Xrm.Sdk;

namespace TSIS2.Plugins
{

    [CrmPluginRegistration(
    MessageNameEnum.Create,
    "msdyn_workorder",
    StageEnum.PreOperation,
    ExecutionModeEnum.Synchronous,
    "",
    "TSIS2.Plugins.PreOperationmsdyn_workorderCreate Plugin",
    1,
    IsolationModeEnum.Sandbox,
    Description = "On Work Order Create, populate the Regulated Entity into the Billing Account using the selected Operation")]
    /// <summary>
    /// PreOperationmsdyn_workorderCreate Plugin.
    /// </summary>    
    public class PreOperationmsdyn_workorderCreate : PluginBase
    {
        //private readonly string postImageAlias = "PostImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PreOperationmsdyn_workorderCreate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public PreOperationmsdyn_workorderCreate(string unsecure, string secure)
            : base(typeof(PreOperationmsdyn_workorderCreate))
        {
            //if (secure != null && !secure.Equals(string.Empty))
            //{

            //}
        }

        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            ITracingService tracingService = localContext.TracingService;
            Entity target = (Entity)context.InputParameters["Target"];

            tracingService.Trace("Entering ExecuteCrmPlugin method.");
            try
            {
                if (target.LogicalName.Equals(msdyn_workorder.EntityLogicalName))
                {
                    tracingService.Trace("Set Category to Planned if making the Work Order from the Planning Module.");
                    if (context.ParentContext != null &&
                        context.ParentContext.InputParameters != null &&
                        context.ParentContext.InputParameters.ContainsKey("x-ms-app-name") &&
                        context.ParentContext.InputParameters["x-ms-app-name"] != null &&
                        context.ParentContext.InputParameters["x-ms-app-name"].ToString() == "ts_OversightPlanningModule")
                    {
                        tracingService.Trace("Setting Category to Planned.");
                        target.Attributes["ovs_rational"] = new EntityReference(ovs_TYRational.EntityLogicalName, new Guid("994c3ec1-c104-eb11-a813-000d3af3a7a7")); //Planned
                    }
                    tracingService.Trace("Set State to Committed if making the Work Order from the ROM application.");
                    if (context.ParentContext != null &&
                        context.ParentContext.InputParameters != null &&
                        context.ParentContext.InputParameters.ContainsKey("x-ms-app-name") &&
                        context.ParentContext.InputParameters["x-ms-app-name"] != null &&
                        context.ParentContext.InputParameters["x-ms-app-name"].ToString() == "ovs_ROM")
                    {
                        tracingService.Trace("Setting State to Committed.");
                        target.Attributes["ts_state"] = new OptionSetValue(717750001); //Committed
                    }

                    if (target.Attributes.Contains("ovs_operationid") && target.Attributes["ovs_operationid"] != null)
                    {
                        EntityReference operation = (EntityReference)target.Attributes["ovs_operationid"];
                        tracingService.Trace("Fetching regulated entity for operation ID: {0}", operation.Id);
                        using (var servicecontext = new Xrm(localContext.OrganizationService))
                        {
                            var regulatedentity = (from tt in servicecontext.ovs_operationSet
                                                   where tt.Id == operation.Id
                                                   select new
                                                   {
                                                       tt.ts_stakeholder
                                                   }).FirstOrDefault();
                            if (regulatedentity != null)
                            {
                                tracingService.Trace("Regulated entity found.");
                                if (regulatedentity.ts_stakeholder != null && regulatedentity.ts_stakeholder.Id != null)
                                {
                                    tracingService.Trace("Setting msdyn_billingaccount to stakeholder ID: {0}", regulatedentity.ts_stakeholder.Id);
                                    target.Attributes["msdyn_billingaccount"] = regulatedentity.ts_stakeholder;
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception e)
            {
                tracingService.Trace("Exception: {0}", e.ToString());
                throw new InvalidPluginExecutionException(e.Message);
            }
        }
    }
}