// <copyright file="PostOperationincidentCreate.cs" company="">
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author>Hong Liu</author>
// <date>9/20/2018 10:21:27 AM</date>
// <summary>Implements the PostOperationincidentCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;

namespace TSIS2.Plugins
{

    [CrmPluginRegistration(
    MessageNameEnum.Create,
    "incident",
    StageEnum.PreOperation,
    ExecutionModeEnum.Synchronous,
    "",
    "TSIS2.Plugins.PreOperationincidentCreate Plugin",
    1,
    IsolationModeEnum.Sandbox,
    Description = "Case Title value should being populated with Case ID.")]
    /// <summary>
    /// PostOperationincidentCreate Plugin.
    /// </summary>    
    public class PreOperationincidentCreate : PluginBase
    {
        //private readonly string postImageAlias = "PostImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PreOperationincidentCreate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public PreOperationincidentCreate(string unsecure, string secure)
            : base(typeof(PreOperationincidentCreate))
        {
            //if (secure != null &&!secure.Equals(string.Empty))
            //{

            //}
        }

        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            Entity target = (Entity)context.InputParameters["Target"];
            IOrganizationService service = localContext.OrganizationService;
            //Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            // Retrieve the system username
            var userId = service.Retrieve("systemuser", context.InitiatingUserId, new ColumnSet("fullname"));
            localContext.Trace("PreOperationincidentCreate: Entering ExecuteCrmPlugin method.");

            try
            {
                localContext.Trace("Plugin executed by user: {0}", userId.GetAttributeValue<string>("fullname"));
                localContext.Trace("Case GUID: {0}", context.PrimaryEntityId);
                localContext.Trace("Case Number: {0}", target.GetAttributeValue<string>("ticketnumber"));
                if (target.LogicalName.Equals(Incident.EntityLogicalName))
                {
                    localContext.Trace("PreOperationincidentCreate: Processing incident entity.");

                    if (target.Attributes.Contains("ticketnumber") && target.Attributes["ticketnumber"] != null && (!target.Attributes.Contains("title") || target.Attributes["title"] == null || target.Attributes["title"].ToString().Length <=0))
                    {
                        localContext.Trace("PreOperationincidentCreate: Setting title attribute.");
                        target.Attributes["title"] = target.Attributes["ticketnumber"];
                    }
                }
            }
            catch (Exception e)
            {
                localContext.Trace("PreOperationincidentCreate: Exception: {0}", e.ToString());
                throw new InvalidPluginExecutionException(e.Message);
            }
            localContext.Trace("PreOperationincidentCreate: Exiting ExecuteCrmPlugin method.");
        }
    }
}