// <copyright file="PreOperationmsdyn_workorderUpdate.cs" company="">PreOperationmsdyn_workorderUpdate
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author>Hong Liu</author>
// <date>9/20/2018 10:21:27 AM</date>
// <summary>Implements the PreOperationts_questionnaireversionUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Xrm.Sdk;

namespace TSIS2.Plugins
{

    [CrmPluginRegistration(
    MessageNameEnum.Update,
    "ts_questionnaireversion",
    StageEnum.PreOperation,
    ExecutionModeEnum.Synchronous,
    "",
    "TSIS2.Plugins.PreOperationts_questionnaireversionUpdate Plugin",
    1,
    IsolationModeEnum.Sandbox,
    Description = "On Questionnaire Version Update, populate the End Date of previous version")]
    /// <summary>
    /// PreOperationts_questionnaireversionUpdate Plugin.
    /// </summary>    
    public class PreOperationts_questionnaireversionUpdate : PluginBase
    {
        public PreOperationts_questionnaireversionUpdate(string unsecure, string secure)
            : base(typeof(PreOperationts_questionnaireversionUpdate))
        {
        }

        protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            ITracingService tracingService = localContext.TracingService;
            IOrganizationService service = localContext.OrganizationService;

            // The InputParameters collection contains all the data passed in the message request.
            if (context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)
            {
                // Obtain the target entity from the input parameters.
                Entity target = (Entity)context.InputParameters["Target"];

                // Obtain the preimage entity
                Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains("PreImage")) ? context.PreEntityImages["PreImage"] : null;

                try
                {
                    if (target.LogicalName.Equals(ts_questionnaireversion.EntityLogicalName))
                    {
                        if (target.Attributes.Contains("ts_effectivestartdate") && target.Attributes["ts_effectivestartdate"] != null)
                        {
                            using (var serviceContext = new Xrm(service))
                            {
                                ts_questionnaireversion currentQuestionnaireVersion = target.ToEntity<ts_questionnaireversion>();
                                var questionnaireVersionList = new List<ts_questionnaireversion>();

                                // Get the selected Questionnaire Version
                                var selectedQuestionnaireVersion = serviceContext.ts_questionnaireversionSet.Where(qv => qv.Id == currentQuestionnaireVersion.Id).FirstOrDefault();

                                // Get the referenced Questionnaire
                                EntityReference questionnaireReference = new EntityReference(ovs_Questionnaire.EntityLogicalName, selectedQuestionnaireVersion.ts_ovs_questionnaire.Id);

                                // Lookup the referenced Questionnaire
                                ovs_Questionnaire questionnaire = serviceContext.ovs_QuestionnaireSet.Where(q => q.Id == questionnaireReference.Id).FirstOrDefault();

                                //List of Questionnaire Version for specific Questionnaire            
                                questionnaireVersionList = serviceContext.ts_questionnaireversionSet.Where(v => v.ts_ovs_questionnaire.Id == questionnaire.Id).ToList();

                                //Update End Date of previous version 
                                for (var i = 0; i < questionnaireVersionList.Count; i++)
                                {
                                    if (questionnaireVersionList[i].ts_effectiveenddate == null && questionnaireVersionList[i].ts_effectivestartdate != null && questionnaireVersionList[i].Id != selectedQuestionnaireVersion.Id && selectedQuestionnaireVersion.ts_effectiveenddate == null)
                                    {
                                        service.Update(new ts_questionnaireversion
                                        {
                                            Id = questionnaireVersionList[i].Id,
                                            ts_effectiveenddate = Convert.ToDateTime(currentQuestionnaireVersion.ts_effectivestartdate).AddDays(-1)
                                        });
                                    }

                                }
                            }
                        }
                        //Store previous definitions incase definition is lost somehow
                        if (target.Attributes.Contains("ts_questionnairedefinition"))
                        {
                            using (var serviceContext = new Xrm(service))
                            {
                                ts_questionnaireversion targetQuestionnaireVersion = target.ToEntity<ts_questionnaireversion>();
                                ts_questionnaireversion currentQuestionnaireVersion = serviceContext.ts_questionnaireversionSet.FirstOrDefault(qv => qv.Id == targetQuestionnaireVersion.Id);

                                target["ts_questionnairedefinitionhistory1"] = currentQuestionnaireVersion.ts_questionnairedefinition;
                                target["ts_questionnairedefinitionhistory2"] = currentQuestionnaireVersion.ts_QuestionnaireDefinitionHistory1;
                                target["ts_questionnairedefinitionhistory3"] = currentQuestionnaireVersion.ts_QuestionnaireDefinitionHistory2;
                                target["ts_questionnairedefinitionhistory4"] = currentQuestionnaireVersion.ts_QuestionnaireDefinitionHistory3;
                                target["ts_questionnairedefinitionhistory5"] = currentQuestionnaireVersion.ts_QuestionnaireDefinitionHistory4;
                            }
                        }
                    }
                }
                catch (Exception e)
                {
                    localContext.TraceWithContext("PreOperationts_questionnaireversionUpdate Plugin: {0}", e);
                    throw new InvalidPluginExecutionException(e.Message);
                }
            }
        }
    }
}